fix compiler error on missing std:string
$ gcc --version | head -n 1
gcc (GCC) 10.0.1 20200328 (experimental)

build/obj/src/export_pdf/export_pdf.o
In file included from src/export_pdf/export_pdf.cpp:1:
src/export_pdf/export_pdf.hpp:6:41: error: ‘string’ is not a member of ‘std’
    6 |                 std::function<void(std::string, double)> cb = nullptr);
      |                                         ^~~~~~
src/export_pdf/export_pdf.hpp:3:1: note: ‘std::string’ is defined in header ‘<string>’; did you forget to ‘#include <string>’?