3rd/dxflib: removed unused field
In file included from 3rd_party/dxflib/dl_writer_ascii.cpp:34:
3rd_party/dxflib/dl_exception.h:52:9: error: private field 'groupCode' is not used [-Werror,-Wunused-private-field]
    int groupCode;