mark overriding member functions
In file included from src/imp/imp_main.cpp:6:
src/imp/imp_board.hpp:21:37: error: 'get_editor_type_for_action' overrides a member function but is not marked 'override'
      [-Werror,-Winconsistent-missing-override]
    ActionCatalogItem::Availability get_editor_type_for_action() const
                                    ^
src/imp/imp.hpp:120:45: note: overridden virtual function is here
    virtual ActionCatalogItem::Availability get_editor_type_for_action() const = 0;