removed unused variables and code
src/board/board_rules_check.cpp:524:14: error: unused variable 'layer' [-Werror,-Wunused-variable]
        auto layer = it.second.layer;
             ^
src/board/board_rules_check.cpp:522:14: error: unused variable 'width' [-Werror,-Wunused-variable]
        auto width = it.second.width;
             ^
src/board/board_rules_check.cpp:523:14: error: unused variable 'net' [-Werror,-Wunused-variable]
        Net *net = it.second.net;
             ^
src/package/package_rules_check.cpp:13:10: error: unused variable 'rule' [-Werror,-Wunused-variable]
    auto rule = dynamic_cast<RulePackageChecks *>(get_rule(RuleID::PACKAGE_CHECKS));
         ^